title: Keidel Clemens Records
permalink: pretty

defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
      comments: true

collections:
 books:
  output: true
  permalink: /:slug
 chapters:
  output: true
  permalink: /:slug
